version: '3.7'

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"  # Expose SonarQube on port 9000
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar # default username - needs to be changed
      - SONAR_JDBC_PASSWORD=sonar # default password - needs to be changed
    depends_on:
      - postgres
    networks:
      - sonarnet

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=sonarqube
      - POSTGRES_USER=sonar # default username - needs to be changed
      - POSTGRES_PASSWORD=sonar # default password - needs to be changed
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data
    networks:
      - sonarnet

networks:
  sonarnet:

volumes:
  postgres_data:
