repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: 'https://github.com/crate-ci/typos'
    rev: v1.8.1
    hooks:
      - id: typos
        args: ['--config', './config/local/typos.toml', './content/']
        files: ^content|i18n

  # Python hooks
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3
