name: GitHub Actions CI

on: [push, pull_request]

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build and test
        run: |
          cd CalculatorJava
          mvn clean test

  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          cd CalculatorPython
          pip install -r requirements.txt  # if you have dependencies
      - name: Run tests
        run: |
          cd CalculatorPython
          python -m unittest discover

  c:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install CUnit
        run: sudo apt-get install -y libcunit1-dev
      - name: Build the project
        run: |
          cd CalculatorC
          make  # Use the Makefile to build the project
      - name: Run tests
        run: |
          cd CalculatorC
          make test  # Use the Makefile to run the tests

  cpp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libgtest-dev  # Install CMake, g++, and Google Test
      - name: Build Google Test
        run: |
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo cp *.a /usr/lib  # Copy the Google Test libraries to /usr/lib
      - name: Create build directory
        run: |
          cd CalculatorCpp
          mkdir build  # Create a build directory
          cd build
          cmake ..  # Run CMake to configure the project
      - name: Build the project
        run: |
          cd CalculatorCpp/build
          make  # Build the project
      - name: Run tests
        run: |
          cd CalculatorCpp/build
          ctest
